//@version=6
indicator("SPT Tool", shorttitle="SPT Tool", overlay=true)

// === INPUT PARAMETERS ===
source = close
fastLength = input.int(12, minval=1, title="Fast Length")
slowLength = input.int(26, minval=1, title="Slow Length")
signalLength = input.int(9, minval=1, title="Signal Length")
spt_line_base_length = 240
spt_line_buffer_multiplier = 0.01
spt_line_buffer_high = ta.atr(10) * spt_line_buffer_multiplier
spt_line_buffer_low = ta.atr(10) * spt_line_buffer_multiplier

// === SUPPORT & RESISTANCE LINES SECTION ===
spt_line_get_dynamic_length() =>
    timeframe_multiplier = timeframe.multiplier
    scale_factor = (timeframe.isintraday) ? (timeframe_multiplier / 1) : 1
    sr_length = spt_line_base_length * scale_factor
    sr_length
spt_line_sr_length = spt_line_get_dynamic_length()
spt_line_sr_length := math.min(spt_line_sr_length, 240)
spt_line_is_swing_high(idx, length) =>
    high[idx] == ta.highest(high, length)
spt_line_is_swing_low(idx, length) =>
    low[idx] == ta.lowest(low, length)
var float spt_line_locked_support = na
var float spt_line_locked_resistance = na
var line spt_line_support_line = na
var line spt_line_resistance_line = na
var label spt_line_support_label = na
var label spt_line_resistance_label = na
for i = 1 to spt_line_sr_length
    if spt_line_is_swing_high(i, spt_line_sr_length)
        spt_line_locked_resistance := high[i]
    if spt_line_is_swing_low(i, spt_line_sr_length)
        spt_line_locked_support := low[i]
if not na(spt_line_support_line)
    line.delete(spt_line_support_line)
if not na(spt_line_resistance_line)
    line.delete(spt_line_resistance_line)
if not na(spt_line_support_label)
    label.delete(spt_line_support_label)
if not na(spt_line_resistance_label)
    label.delete(spt_line_resistance_label)
if (bar_index >= spt_line_sr_length)
    if not na(spt_line_locked_support)
        spt_line_support_line := line.new(x1=bar_index - spt_line_sr_length, y1=spt_line_locked_support, x2=bar_index, y2=spt_line_locked_support, color=color.orange, width=4, style=line.style_solid)
    if not na(spt_line_locked_resistance)
        spt_line_resistance_line := line.new(x1=bar_index - spt_line_sr_length, y1=spt_line_locked_resistance, x2=bar_index, y2=spt_line_locked_resistance, color=color.purple, width=4, style=line.style_solid)
spt_line_precision = 5
spt_line_support_text = "Support: " + str.tostring(spt_line_locked_support, "#." + str.repeat("0", spt_line_precision))
spt_line_resistance_text = "Resistance: " + str.tostring(spt_line_locked_resistance, "#." + str.repeat("0", spt_line_precision))
if (bar_index == ta.highest(bar_index, 1)) 
    if not na(spt_line_locked_support)
        spt_line_support_label := label.new(x=bar_index, y=spt_line_locked_support, text=spt_line_support_text, color=color.orange, textcolor=color.white, style=label.style_label_left, size=size.normal)
    if not na(spt_line_locked_resistance)
        spt_line_resistance_label := label.new(x=bar_index, y=spt_line_locked_resistance, text=spt_line_resistance_text, color=color.purple, textcolor=color.white, style=label.style_label_left, size=size.normal)

// === BACKGROUND COLOR SECTION ===
macdLine = ta.ema(source, fastLength) - ta.ema(source, slowLength)
signalLine = ta.ema(macdLine, signalLength)
histogram = macdLine - signalLine
isBullishMACD = macdLine > signalLine
isBearishMACD = macdLine < signalLine
trendBullish = isBullishMACD and macdLine > 0
trendBearish = isBearishMACD and macdLine < 0
trendNeutral = not trendBullish and not trendBearish
bgColorBull = color.new(color.green, 75)
bgColorBear = color.new(color.red, 75)
bgColorNeutral = color.new(color.gray, 75)
bgcolor(trendBullish ? bgColorBull : na, title="Bullish Background")
bgcolor(trendBearish ? bgColorBear : na, title="Bearish Background")
bgcolor(trendNeutral ? bgColorNeutral : na, title="Neutral Background")

// === Trend Conditions ===
spt_trend_current_close = request.security(syminfo.tickerid, timeframe.period, close)
spt_trend_tenkan_sen = request.security(syminfo.tickerid, timeframe.period, (ta.highest(high, 9) + ta.lowest(low, 9)) / 2)
spt_trend_kijun_sen = request.security(syminfo.tickerid, timeframe.period, (ta.highest(high, 26) + ta.lowest(low, 26)) / 2)
spt_trend_senkou_span_a = request.security(syminfo.tickerid, timeframe.period, (spt_trend_tenkan_sen + spt_trend_kijun_sen) / 2)
spt_trend_senkou_span_b = request.security(syminfo.tickerid, timeframe.period, (ta.highest(high, 52) + ta.lowest(low, 52)) / 2)
spt_trend_uptrend = spt_trend_current_close > spt_trend_senkou_span_a and spt_trend_current_close > spt_trend_senkou_span_b
spt_trend_downtrend = spt_trend_current_close < spt_trend_senkou_span_a and spt_trend_current_close < spt_trend_senkou_span_b
var string spt_trend_current_trend = "Neutral" 
var int trend_start_bar = na
var int uptrend_duration = 0
var int downtrend_duration = 0
var int uptrend_count = 0
var int downtrend_count = 0
var int consecutive_uptrend_bars = 0
var int consecutive_downtrend_bars = 0
confirmation_threshold = 4  
if spt_trend_uptrend
    consecutive_uptrend_bars := consecutive_uptrend_bars + 1
    consecutive_downtrend_bars := 0 
    if spt_trend_current_trend != "Uptrend" and consecutive_uptrend_bars >= confirmation_threshold
        spt_trend_current_trend := "Uptrend"
        trend_start_bar := bar_index  
        uptrend_duration := 0  
        consecutive_uptrend_bars := 0  
    else
        consecutive_uptrend_bars := math.min(consecutive_uptrend_bars, confirmation_threshold) 
if spt_trend_downtrend
    consecutive_downtrend_bars := consecutive_downtrend_bars + 1
    consecutive_uptrend_bars := 0  
    if spt_trend_current_trend != "Downtrend" and consecutive_downtrend_bars >= confirmation_threshold
        spt_trend_current_trend := "Downtrend"
        trend_start_bar := bar_index 
        downtrend_duration := 0  
        consecutive_downtrend_bars := 0 
    else
        consecutive_downtrend_bars := math.min(consecutive_downtrend_bars, confirmation_threshold) 
if spt_trend_current_trend == "Uptrend"
    uptrend_duration := bar_index - trend_start_bar
if spt_trend_current_trend == "Downtrend"
    downtrend_duration := bar_index - trend_start_bar
max_bars = 365 
var float avg_uptrend_bars = na
var float avg_downtrend_bars = na
if bar_index >= max_bars
    if spt_trend_current_trend == "Uptrend"
        uptrend_count := uptrend_count + 1
        avg_uptrend_bars := na(avg_uptrend_bars) ? uptrend_duration : (avg_uptrend_bars * (uptrend_count - 1) + uptrend_duration) / uptrend_count 
    if spt_trend_current_trend == "Downtrend"
        downtrend_count := downtrend_count + 1
        avg_downtrend_bars := na(avg_downtrend_bars) ? downtrend_duration : (avg_downtrend_bars * (downtrend_count - 1) + downtrend_duration) / downtrend_count  
var string previous_trend = na
trend_changed = (spt_trend_current_trend != previous_trend)
previous_trend := spt_trend_current_trend
uptrend_arrow = spt_trend_current_trend == "Uptrend" and trend_changed
downtrend_arrow = spt_trend_current_trend == "Downtrend" and trend_changed
plotshape(uptrend_arrow, title="Uptrend Arrow", style=shape.labelup, location=location.belowbar, color=color.green, size=size.small, text="▲")
plotshape(downtrend_arrow, title="Downtrend Arrow", style=shape.labeldown, location=location.abovebar, color=color.red, size=size.small, text="▼")
var table spt_trend_table_right = table.new(position.bottom_right, 2, 2)
if barstate.islast
    table.cell(spt_trend_table_right, 0, 0, "Trend", text_size=size.normal, text_color=color.white, bgcolor=color.blue)
    table.cell(spt_trend_table_right, 0, 1, "Bars now:", text_size=size.normal, text_color=color.white, bgcolor=color.blue)
    table.cell(spt_trend_table_right, 1, 0, spt_trend_current_trend, text_size=size.normal, text_color=color.black, bgcolor=color.white)
    table.cell(spt_trend_table_right, 1, 1, str.tostring(uptrend_duration), text_size=size.normal, text_color=color.black, bgcolor=color.white)
var table spt_trend_table_left = table.new(position.bottom_left, 2, 2)
if barstate.islast and bar_index >= max_bars    
    table.cell(spt_trend_table_left, 0, 0, "AVG UP:", text_size=size.normal, text_color=color.white, bgcolor=color.blue)
    table.cell(spt_trend_table_left, 0, 1, "AVG DOWN:", text_size=size.normal, text_color=color.white, bgcolor=color.blue)
    table.cell(spt_trend_table_left, 1, 0, str.tostring(math.round(avg_uptrend_bars)), text_size=size.normal, text_color=color.green, bgcolor=color.white)
    table.cell(spt_trend_table_left, 1, 1, str.tostring(math.round(avg_downtrend_bars)), text_size=size.normal, text_color=color.red, bgcolor=color.white)

// === Short/Long term trend ===
spt_SL_short_term_days = 90  
spt_SL_long_term_days = 365 
spt_SL_daily_short_term_ema = request.security(syminfo.tickerid, "D", ta.ema(close, spt_SL_short_term_days))
spt_SL_daily_long_term_ema = request.security(syminfo.tickerid, "D", ta.ema(close, spt_SL_long_term_days))
spt_SL_4hr_short_term_ema = request.security(syminfo.tickerid, "240", ta.ema(close, spt_SL_short_term_days))
spt_SL_4hr_long_term_ema = request.security(syminfo.tickerid, "240", ta.ema(close, spt_SL_long_term_days))
trend_margin = 0.002 
spt_SL_daily_short_trend = close > spt_SL_daily_short_term_ema * (1 + trend_margin) ? 1 : (close < spt_SL_daily_short_term_ema * (1 - trend_margin) ? -1 : 0)
spt_SL_daily_long_trend = close > spt_SL_daily_long_term_ema * (1 + trend_margin) ? 1 : (close < spt_SL_daily_long_term_ema * (1 - trend_margin) ? -1 : 0)
spt_SL_4hr_short_trend = close > spt_SL_4hr_short_term_ema * (1 + trend_margin) ? 1 : (close < spt_SL_4hr_short_term_ema * (1 - trend_margin) ? -1 : 0)
spt_SL_4hr_long_trend = close > spt_SL_4hr_long_term_ema * (1 + trend_margin) ? 1 : (close < spt_SL_4hr_long_term_ema * (1 - trend_margin) ? -1 : 0)
spt_SL_short_trend = (spt_SL_daily_short_trend == spt_SL_4hr_short_trend) ? spt_SL_daily_short_trend : -1
spt_SL_long_trend = (spt_SL_daily_long_trend == spt_SL_4hr_long_trend) ? spt_SL_daily_long_trend : -1
spt_SL_short_strength = spt_SL_short_trend == 1 ? (close > spt_SL_4hr_short_term_ema * (1 + trend_margin) ? 2 : 1) : (spt_SL_short_trend == 0 ? 0 : -2)
spt_SL_long_strength = spt_SL_long_trend == 1 ? (close > spt_SL_4hr_long_term_ema * (1 + trend_margin) ? 2 : 1) : (spt_SL_long_trend == 0 ? 0 : -2)
spt_SL_short_color = spt_SL_short_strength == 2 ? color.green : spt_SL_short_strength == 1 ? color.black : spt_SL_short_strength == -1 ? color.red : color.black
spt_SL_long_color = spt_SL_long_strength == 2 ? color.green : spt_SL_long_strength == 1 ? color.black : spt_SL_long_strength == -1 ? color.red : color.black
var table spt_SL_trend_table = table.new(position.top_right, 2, 2, bgcolor=color.new(color.white, 90), frame_color=color.new(color.black, 90))
table.cell(spt_SL_trend_table, 0, 0, "Long:", text_color=color.white, bgcolor=color.blue)
table.cell(spt_SL_trend_table, 0, 1, spt_SL_long_strength == 2 ? "Bullish" : spt_SL_long_strength == 1 ? "Bullish" : spt_SL_long_strength == 0 ? "Neutral" : spt_SL_long_strength == -1 ? "Bearish" : "Bearish", text_color=spt_SL_long_color, bgcolor=color.white)
table.cell(spt_SL_trend_table, 1, 0, "Short:", text_color=color.white, bgcolor=color.blue)
table.cell(spt_SL_trend_table, 1, 1, spt_SL_short_strength == 2 ? "Bullish" : spt_SL_short_strength == 1 ? "Bullish" : spt_SL_short_strength == 0 ? "Neutral" : spt_SL_short_strength == -1 ? "Bearish" : "Bearish", text_color=spt_SL_short_color, bgcolor=color.white)
spt_LINE_1m = 1440    
spt_LINE_5m = 288     
spt_LINE_1h1 = 1200   
spt_LINE_1h2 = 4800   
spt_LINE_1hNF1 = 150  
spt_LINE_1hNF2 = 365  
spt_LINE_4h1 = 300   
spt_LINE_4h2 = 1200   
spt_LINE_1D1 = 50     
spt_LINE_1D2 = 200    
spt_LINE_1DNF1 = 8    
spt_LINE_1DNF2 = 21   
spt_LINE_1W = 52     
spt_LINE_1M = 84     
ema_src = close
var int spt_LINE_ema_length_1 = na
if timeframe.isintraday and timeframe.multiplier == 1
    spt_LINE_ema_length_1 := 1
else if timeframe.isintraday and timeframe.multiplier == 5
    spt_LINE_ema_length_1 := 1
else if timeframe.isintraday and timeframe.multiplier == 60
    spt_LINE_ema_length_1 := spt_LINE_1hNF1
else if timeframe.isintraday and timeframe.multiplier == 240
    spt_LINE_ema_length_1 := 1
else if timeframe.isdaily
    spt_LINE_ema_length_1 := spt_LINE_1DNF1
else if timeframe.isweekly
    spt_LINE_ema_length_1 := 1
else if timeframe.ismonthly
    spt_LINE_ema_length_1 := 1
else
    spt_LINE_ema_length_1 := 1
var int spt_LINE_ema_length_2 = na
if timeframe.isintraday and timeframe.multiplier == 1
    spt_LINE_ema_length_2 := 1
else if timeframe.isintraday and timeframe.multiplier == 5
    spt_LINE_ema_length_2 := 1
else if timeframe.isintraday and timeframe.multiplier == 60
    spt_LINE_ema_length_2 := spt_LINE_1hNF2
else if timeframe.isintraday and timeframe.multiplier == 240
    spt_LINE_ema_length_2 := 1
else if timeframe.isdaily
    spt_LINE_ema_length_2 := spt_LINE_1DNF2
else if timeframe.isweekly
    spt_LINE_ema_length_2 := 1
else if timeframe.ismonthly
    spt_LINE_ema_length_2 := 1
else
    spt_LINE_ema_length_2 := 1
var int spt_LINE_ema_length_3 = na
if timeframe.isintraday and timeframe.multiplier == 1
    spt_LINE_ema_length_3 := spt_LINE_1m
else if timeframe.isintraday and timeframe.multiplier == 5
    spt_LINE_ema_length_3 := spt_LINE_5m
else if timeframe.isintraday and timeframe.multiplier == 60
    spt_LINE_ema_length_3 := 1
else if timeframe.isintraday and timeframe.multiplier == 240
    spt_LINE_ema_length_3 := spt_LINE_4h1
else if timeframe.isdaily
    spt_LINE_ema_length_3 := spt_LINE_1D1
else if timeframe.isweekly
    spt_LINE_ema_length_3 := spt_LINE_1W
else if timeframe.ismonthly
    spt_LINE_ema_length_3 := spt_LINE_1M
else
    spt_LINE_ema_length_3 := 1
var int spt_LINE_ema_length_4 = na
if timeframe.isintraday and timeframe.multiplier == 1
    spt_LINE_ema_length_4 := 1
else if timeframe.isintraday and timeframe.multiplier == 5
    spt_LINE_ema_length_4 := 1
else if timeframe.isintraday and timeframe.multiplier == 60
    spt_LINE_ema_length_4 := 1
else if timeframe.isintraday and timeframe.multiplier == 240
    spt_LINE_ema_length_4 := spt_LINE_4h2
else if timeframe.isdaily
    spt_LINE_ema_length_4 := spt_LINE_1D2
else if timeframe.isweekly
    spt_LINE_ema_length_4 := 1
else if timeframe.ismonthly
    spt_LINE_ema_length_4 := 1
else
    spt_LINE_ema_length_4 := 1
plot(spt_LINE_ema_length_1 == 1 ? na : ta.ema(ema_src, spt_LINE_ema_length_1), title="8D / 150h", style=plot.style_line, linewidth=2, color=color.new(#42BDA8, 50))
plot(spt_LINE_ema_length_2 == 1 ? na : ta.ema(ema_src, spt_LINE_ema_length_2), title="21D / 365h", style=plot.style_line, linewidth=3, color=color.new(#FFEE58, 40))
plot(spt_LINE_ema_length_3 == 1 ? na : ta.ema(ema_src, spt_LINE_ema_length_3), title="1D / 50D / 52W / 7Y", style=plot.style_circles, linewidth=1, color=color.new(#26C6DA, 5))
plot(spt_LINE_ema_length_4 == 1 ? na : ta.ema(ema_src, spt_LINE_ema_length_4), title="200D", style=plot.style_circles, linewidth=1, color=color.new(#EC407A, 5))
var table SPT_EMA = table.new(position.middle_left, 1, 5)
table.cell(SPT_EMA, 0, 0, "EMA LINES:", bgcolor=color.white, text_color=color.black)
table.cell(SPT_EMA, 0, 1, "8D / 150h", bgcolor=color.new(#42BDA8, 50), text_color=color.white)
table.cell(SPT_EMA, 0, 2, "21D / 365h", bgcolor=color.new(#FFEE58, 40), text_color=color.white)
table.cell(SPT_EMA, 0, 3, "1D / 50D / 52W / 7Y", bgcolor=color.new(#26C6DA, 5), text_color=color.white)
table.cell(SPT_EMA, 0, 4, "200D", bgcolor=color.new(#EC407A, 5), text_color=color.white)
